# Configuration du serveur user-manager
server.port=8085

# Liaison avec le conteneur PostgreSQL de schoollink
spring.datasource.url=jdbc:postgresql://localhost:5432/usermanager
spring.datasource.username=schoollink
spring.datasource.password=schoollink_secret

# Configuration Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true